name: releases

env:
  CI_REGISTRY: ghcr.io
  GO_REQUIRED_VERSION: "1.20"

on: push

jobs:
  distribute-images:
    name: 🚢 Distribute images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CI registry login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | \
            docker login ${{ env.CI_REGISTRY }} -u ${{ github.repository_owner }} --password-stdin

      - name: CI image build/publish
        run: |
          git submodule update --init

          # https://github.com/crossplane/crossplane/issues/3051#issuecomment-1110818830
          #echo "" >> package/crossplane.yaml
          #cat package/crds/*.yaml >> package/crossplane.yaml

          # Install up
          curl -sL https://cli.upbound.io | sh
          sudo mv up /usr/local/bin
          up --version

          # Build image
          up xpkg build -f ./package -o out.xpkg

          # Push image
          imagePath=${{ format('{0}/{1}:{2}', env.CI_REGISTRY, github.repository, github.sha) }}
          imageLatestPath=${{ format('{0}/{1}:latest', env.CI_REGISTRY, github.repository) }}
          up xpkg push $imagePath -f out.xpkg
          up xpkg push $imageLatestPath -f out.xpkg